# Generated by Django 4.2.3 on 2023-07-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_fathers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fathers_name',
        ),
    ]
